// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/azsb/blob.proto

package azsb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Blob struct {
	Packets              map[string][]byte `protobuf:"bytes,1,rep,name=packets,proto3" json:"packets,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Blob) Reset()         { *m = Blob{} }
func (m *Blob) String() string { return proto.CompactTextString(m) }
func (*Blob) ProtoMessage()    {}
func (*Blob) Descriptor() ([]byte, []int) {
	return fileDescriptor_2467783680d92de5, []int{0}
}

func (m *Blob) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Blob.Unmarshal(m, b)
}
func (m *Blob) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Blob.Marshal(b, m, deterministic)
}
func (m *Blob) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Blob.Merge(m, src)
}
func (m *Blob) XXX_Size() int {
	return xxx_messageInfo_Blob.Size(m)
}
func (m *Blob) XXX_DiscardUnknown() {
	xxx_messageInfo_Blob.DiscardUnknown(m)
}

var xxx_messageInfo_Blob proto.InternalMessageInfo

func (m *Blob) GetPackets() map[string][]byte {
	if m != nil {
		return m.Packets
	}
	return nil
}

func init() {
	proto.RegisterType((*Blob)(nil), "azsb.Blob")
	proto.RegisterMapType((map[string][]byte)(nil), "azsb.Blob.PacketsEntry")
}

func init() { proto.RegisterFile("src/azsb/blob.proto", fileDescriptor_2467783680d92de5) }

var fileDescriptor_2467783680d92de5 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2e, 0x4a, 0xd6,
	0x4f, 0xac, 0x2a, 0x4e, 0xd2, 0x4f, 0xca, 0xc9, 0x4f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0x62, 0x01, 0x09, 0x28, 0x95, 0x72, 0xb1, 0x38, 0xe5, 0xe4, 0x27, 0x09, 0x19, 0x72, 0xb1, 0x17,
	0x24, 0x26, 0x67, 0xa7, 0x96, 0x14, 0x4b, 0x30, 0x2a, 0x30, 0x6b, 0x70, 0x1b, 0x89, 0xeb, 0x81,
	0xe4, 0xf5, 0x40, 0x92, 0x7a, 0x01, 0x10, 0x19, 0xd7, 0xbc, 0x92, 0xa2, 0xca, 0x20, 0x98, 0x3a,
	0x29, 0x2b, 0x2e, 0x1e, 0x64, 0x09, 0x21, 0x01, 0x2e, 0xe6, 0xec, 0xd4, 0x4a, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0xce, 0x20, 0x10, 0x53, 0x48, 0x84, 0x8b, 0xb5, 0x2c, 0x31, 0xa7, 0x34, 0x55, 0x82,
	0x49, 0x81, 0x51, 0x83, 0x27, 0x08, 0xc2, 0xb1, 0x62, 0xb2, 0x60, 0x4c, 0x62, 0x03, 0xbb, 0xc1,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xfc, 0x73, 0xca, 0x9a, 0x00, 0x00, 0x00,
}
